#define LUA_FOLDER  "src/lua"
#define OUTPUT_LUA "src/c/globals.lua_code.c"
#define LUA_VAR_NAME  "lua_code"
#define LUA_START_POINT  "main.lua"
#define FINAL_OUPTUT_LINUX  "../build.out"
#define FINAL_OUPTUT_WINDOWS  "../build.exe"
#define SRC_C_FOLDER "src/c"
